Basic Dataframe Understanding

In [ ]:
# csv file import from github
import pandas as pd
url = "https://raw.githubusercontent.com/mohammedmubarak-ops/ds-aiml/main/file2.json"
df = pd.read_json(url)
df
# head  -> starting 5 rows
df.head(2)
# head -> 2 rows data
df.head(-3)
# head -> negative number

In [ ]:
#SHAPE
import pandas as pd
url = "https://raw.githubusercontent.com/mohammedmubarak-ops/ds-aiml/main/file2.json"
df = pd.read_json(url)
df = pd.Series(data=[10,20,30,40,50])
df.shape

(5,)

In [ ]:
#INFO
import pandas as pd
url = "https://raw.githubusercontent.com/mohammedmubarak-ops/ds-aiml/main/file2.json"
df = pd.read_json(url)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      str
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [1]:
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/mohammedmubarak-ops/ds-aiml/main/file2.json"
df = pd.read_json(url)
df["salary"]=[100,200,300,np.nan,500]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      str
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
 3   salary   4 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 292.0 bytes

In [7]:
#RENAME
import pandas as pd
url = "https://raw.githubusercontent.com/mohammedmubarak-ops/ds-aiml/main/file2.json"
df = pd.read_json(url)
df.rename(columns={"name": "student_name"},inplace=True)
#inplace to chnge in original data
df

  student_name  roll no  marks
0      dheeraj      123     10
1        kunal     1234     20
2     abhishek    12345     30
3      praveen    12356     40
4       anjali  1234567     50

In [11]:
#DESCRIBE
import pandas as pd
url = "https://raw.githubusercontent.com/mohammedmubarak-ops/ds-aiml/main/file2.json"
df = pd.read_json(url)
df.describe()

            roll no      marks
count  5.000000e+00   5.000000
mean   2.521250e+05  30.000000
std    5.492329e+05  15.811388
min    1.230000e+02  10.000000
25%    1.234000e+03  20.000000
50%    1.234500e+04  30.000000
75%    1.235600e+04  40.000000
max    1.234567e+06  50.000000

In [ ]:
import pandas as pd
data = {
 "Emp ID": [101, 102, 103, 104, 105, 106],
 "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"], "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"], "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
 "Experience": [2, 3, 5, 4, 1, 3]
}
df=pd.DataFrame(data)
print(df)
#HEAD
print(df.head(2))
print(df.head(-2))
 
#TAIL
print(df.tail(3))
print(df.tail(-3))
 
#SHAPE
print(df.shape)
 
#INFO
print(df.info())
 
#VERBOSE
df.info(verbose=True)
df.info(verbose=False)
 
#RENAME
df.rename(columns={"Name": "Emp_Name"}, inplace=True)
print(df)
 
#DESCRIBE
df.describe()

   Emp ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
   Emp ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
   Emp ID  Name Department  Salary  Experience
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp ID  Name Department  Salary  Experience
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
(6, 5)
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp ID      6 non-null      int64
 1   Name        6 non-null      str
 2   Department  6 non-null      str
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), str(2)
memory usage: 372.0 bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp ID      6 non-null      int64
 1   Name        6 non-null      str
 2   Department  6 non-null      str
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), str(2)
memory usage: 372.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 5 entries, Emp ID to Experience
dtypes: int64(3), str(2)
memory usage: 372.0 bytes
   Emp ID Emp_Name Department  Salary  Experience
0     101     Amit         IT   50000           2
1     102     Riya         HR   45000           3
2     103      Raj    Finance   60000           5
3     104     Sara         IT   55000           4
4     105     John      Sales   48000           1
5     106     Neha         HR   52000           3

           Emp ID        Salary  Experience
count    6.000000      6.000000    6.000000
mean   103.500000  51666.666667    3.000000
std      1.870829   5316.640543    1.414214
min    101.000000  45000.000000    1.000000
25%    102.250000  48500.000000    2.250000
50%    103.500000  51000.000000    3.000000
75%    104.750000  54250.000000    3.750000
max    106.000000  60000.000000    5.000000

OPERATIONS ON COLUMNS

In [27]:
import pandas as pd
url = "https://raw.githubusercontent.com/mohammedmubarak-ops/ds-aiml/main/file2.json"
df = pd.read_json(url)
# get single column data
df["name"]
# add single column
df["salary"] = df["marks"] + 100
# add single column
df["salary"] = [100,200,300,400,500]
print(df)

       name  roll no  marks  salary
0   dheeraj      123     10     100
1     kunal     1234     20     200
2  abhishek    12345     30     300
3   praveen    12356     40     400
4    anjali  1234567     50     500

In [ ]:
import pandas as pd
d = {
    "name": ["vishal","virat","vineet"],
    "salary": [100,200,300]
}
df = pd.DataFrame(data=d)
# df["marks"] = [10,20,30]
df["marks"] = df["salary"] / 2
print(df)

     name  salary  marks
0  vishal     100   50.0
1   virat     200  100.0
2  vineet     300  150.0